### ISSUE TITLE
Can we create our own xml or json structure?

### ISSUE THREAD

**Issue by kalismeras61** [OndrejKunc/flutter_dynamic_forms#47]
Hello, 
I have one project based on create dynamic form from xml/json. I saw your repo and it look awesome.
But i don't have more detail in json object and my json structure is very simple like below.  just need 3 type of element. Input's for strings,float and intergers, Date for dates and DropDown for List's.( Searcable dropdown) 

So can create my own structure ? or i must change my server response to your structure? 

> `{
>     "data": [
>         {
>             "type": "Checkbox",
>             "label": "Cari Hesaplar",
>             "value": 1,
>             "list_fields": [
>                 {
>                     "label": "Label 1",
>                     "value": 1
>                 },
>                 {
>                     "label": "Label 2",
>                     "value": 2
>                 },
>                 {
>                     "label": "Label 3",
>                     "value": 3
>                 }
>             ]
>         },
>         {
>             "type": "Input",
>             "label": "Sözleşme No"
>         },
>         {
>             "type": "Date",
>             "label": "Sözleşme Tarihi"
>         },
>         {
>             "type": "Date",
>             "label": "Sözleşme Bitiş Tarihi"
>         }
>     ]
> }`

**Comment by OndrejKunc** [comment]
Hi,
thanks for opening the issue.
I am aware that documentation about exact JSON and XML format is not very good right now.

I think easiest way for you is to change your server response to look something like the [json in the example project](https://github.com/OndrejKunc/flutter_dynamic_forms/blob/master/packages/flutter_dynamic_forms_components/example/assets/test_form1.json). You would need to wrap your components inside some root component (for example [container](https://github.com/OndrejKunc/flutter_dynamic_forms/tree/master/packages/flutter_dynamic_forms_components/lib/src/components/container)) instead of the data property. Also, you need to change "type" for "@name" and start lower case letters in component names. I am also a little bit confused about the "list_fields" property inside the checkbox. Shouldn't it be outside the checkbox?

If for some reason you can't easily change your server response, it is still quite easy to write your own parsing logic. You would just need to implement those [two classes](https://github.com/OndrejKunc/flutter_dynamic_forms/tree/master/packages/dynamic_forms/lib/src/parser/json) and pass it to the `FormManagerBuilder`. If you are interested in the decision behind JSON parser you can check this [thread](https://github.com/OndrejKunc/flutter_dynamic_forms/issues/19).

In your case, I would also probably recommend not to use `flutter_dynamic_forms_components`  and write your components from scratch, so you can have greater control over all the properties. You would just need to reference `flutter_dynamic_forms`. See the [other example project](https://github.com/OndrejKunc/flutter_dynamic_forms/tree/master/packages/flutter_dynamic_forms/example) which implements its own small set of components.

**Comment by kalismeras61** [comment]
@OndrejKunc  thank you for your detailed answer. I think i need to create my own components as i see i just need only 3 class for each component.? When i created my own components only i can use  this package parserNode parameters? isnt it?

**Comment by kalismeras61** [comment]
Hi @OndrejKunc , i created my own components and for dropdown i just used your parser and model except renderer part. I created my own searchable dropdown widget but i saw one problem. 

The problem is when i select any item on list on android it will updated the default value but on iphone emulator does not indicate change to default value. ( i printed selected value it looks true)

Did you test it your plugin both of android and ios?

**Comment by kalismeras61** [comment]
> Hi @OndrejKunc , i created my own components and for dropdown i just used your parser and model except renderer part. I created my own searchable dropdown widget but i saw one problem.
> 
> The problem is when i select any item on list on android it will updated the default value but on iphone emulator does not indicate change to default value. ( i printed selected value it looks true)
> 
> Did you test your plugin both of android and ios side?

I was using Iphone 11 emulator which is have ios 13 , i test it with Iphone 8 it seems work. Do you think it is flutter issue?

**Comment by kalismeras61** [comment]
Hi @OndrejKunc i have been good at many things with this package but i'am  stuck on one problem.
I get my form details from server, there is no problem at all i created my own inputs, dropdown and date components. 

    Lets say i have search form (look at  below xml as you see)and have one date element but i have to sent server  one id but 2 value. Because it is search form if the user selects only the start date, they will see the today current values.if they selects an end date, they  will see the values before the end date. if users selects the start and end date, they will be able to search between the two dates.

The problem is i just get only one date element from server but i have to send one id but two value to server. Do you have an idea about that ?

Note : Btw i will send pull request for date component.


<?xml version="1.0" encoding="UTF-8"?>
<form id="form1">
  <input id="Sözleşme No" textInputType="text">
  </input>
  <input id="Evrak No" textInputType="number">
  </input>
  <dropdownButton id="Cari Hesaplar" value="Kets Bilgisayar">
    <dropdownOption value="Kets Bilgisayar" label="Kets Bilgisayar"/>
    <dropdownOption value="Vitek Otomasyon" label="Vitek Otomasyon"/>
    <dropdownOption value="RCT Solutions" label="RCT Solutions"/>
  </dropdownButton>
  <date id ="Sözleşme Tarihi" label="Sözleşme Tarihi" value=""></date>
</form>

**Comment by OndrejKunc** [comment]
Hi,
I'm glad to hear about your progress!

So I suppose you are using the `List<FormItemValue> data = formManager.getFormData()` to collect your data from the form right? 
This method will go through the whole form and collects all the properties, which are marked as an `isImmutable: false` in the parser. You can have multiple properties marked `isImmutable: false` on one component so there will be one  `FormItemValue` for each of your property.

I would simply add two properties on your date component model, something like startDate and endDate and set their default values in the parser object and set them as `isImmutable: false`. It is not a problem if you don't have those properties filled in your XML, because they will be initialized to the default values via the parser. And once you have them on the model, you can fill them via `ChangeValueEvent` in your renderer. 
Then you can collect those values using `formManager.getFormData()` so you will have 2 FormItemValues, one for startDate and one for endDate both with the same Id. I don't know how you send those data back to your server, but you can take those objects and group them by Id and send them together.

Hope this helps.

**Comment by kalismeras61** [comment]
@OndrejKunc  i tired someting but i get this error

` Exception: Can't get expressions for value `
 Could you help me for right implementation ?
 Here is my model class;
 https://dpaste.de/mWs5 
 Here is the my parser
https://dpaste.de/1epZ
And here is the my renderer part ( it is a little bit complicated);
https://dpaste.de/tquk

Default xml is below;
```

<?xml version="1.0" encoding="UTF-8"?>
<form id="form1">
  <input id="Sözleşme No" textInputType="text">
  </input>
  <input id="Evrak No" textInputType="number">
  </input>
  <dropdownButton id="Cari Hesaplar" value="Kets Bilgisayar">
    <dropdownOption value="Kets Bilgisayar" label="Kets Bilgisayar"/>
    <dropdownOption value="Vitek Otomasyon" label="Vitek Otomasyon"/>
    <dropdownOption value="RCT Solutions" label="RCT Solutions"/>
  </dropdownButton>
  <date id ="Sözleşme Tarihi" label="Sözleşme Tarihi" startDate="" endDate=""></date>
</form>
```

**Comment by kalismeras61** [comment]
It was m fault :) I found the problem. ChangeValueEvent send default propertyName "value" so why i get this error. 

   ```
 dispatcher(
                                  ChangeValueEvent(
                                    value: picked1.toString(),
                                    elementId: element.id,
                                    propertyName:
                                        model.Date.endValuePropertyName,
                                  ),
                                );
```

**Comment by OndrejKunc** [comment]
Awesome :)
Yeah, that default property name "value" is something we consider to remove anyway. It seemed like a good idea at the beginning but it can be quite confusing.
