### ISSUE TITLE
Where can i see your xml schema properties?

### ISSUE THREAD

**Issue by kalismeras61** [OndrejKunc/flutter_dynamic_forms#48]
Is there any doc for your schemes? Which properties can i use? 

And also default component text needs also border properties.

**Comment by OndrejKunc** [comment]
I assume you are talking about the components scheme in the `flutter_dynamic_forms_components` package. It is not documented, but all the components are defined in the yaml files like this [checkbox](https://github.com/OndrejKunc/flutter_dynamic_forms/blob/master/packages/flutter_dynamic_forms_components/lib/src/components/check_box/check_box.yaml). You can check each folder and see the properties. Those yaml files are also used to generate model and parser via [generator](https://github.com/OndrejKunc/flutter_dynamic_forms/tree/master/packages/dynamic_forms_generator), but it is an optional step and you can always write it by hand.

The  `flutter_dynamic_forms_components` package now serves more like an example package because it is difficult to cover all the properties that can be useful to everyone so I would recommend always roll your own set of components with the properties you need. Or you can make a merge request to add this property :).
