### ISSUE TITLE
Expressions crach on id containe "_" or "."

### ISSUE THREAD

**Issue by mmmcorpsvit** [OndrejKunc/flutter_dynamic_forms#92]
Please add warning like this:

```
Warning! 
Id tag cannon contain "_" or "."!
```

i mean there 
```html
<textField id="user.First_Name" label="Enter your first name" value="super_user">    
```

this behavior crash expressions parser

**Comment by OndrejKunc** [comment]
I added `_` as an allowed character in the identifier. The `.` cannot be used, because it can be used in the expressions to reference properties so there will be a conflict.
I added this log to the parser, whenever there is a prohibited character:
```
  developer.log(
    'Warning: Invalid identifier \'$id\' for element type $TFormElement in FormElementParser.\n'
    'Only alphanumerics characters and underscores are allowed and identifiers cannot start with a number.',
    level: 900, // 900 relates to Warning according to the package:logging
  );
```
It is already merged and published together with the null safety version, so I am closing it now.
